---
apiVersion: v1
kind: Service
metadata:
  name: api1
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  api1_mapping
      prefix: /api1/
      service: api1
spec:
  selector:
    app: api1
  ports:
  - port: 80
    name: http-api1
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: eu.gcr.io/parcel-vision/spike-ambassador-api:3.0
        ports:
        - containerPort: 8010
     





