---
apiVersion: v1
kind: Service
metadata:
  name: app1
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  app1_mapping
      prefix: /app1/
      service: app1
spec:
  selector:
    app: app1
  ports:
  - port: 80
    name: http-app1
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: eu.gcr.io/parcel-vision/spike-ambassador-application:1.0
        ports:
        - name: http-api
          containerPort: 8020
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi