##################################################################################################
# Application service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
  - port: 8020
    name: http
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: app
        image: eu.gcr.io/parcel-vision/spike-ambassador-application-v1:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        version: v2
    spec:
      containers:
      - name: app
        image: eu.gcr.io/parcel-vision/spike-ambassador-application-v2:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020