---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pvr-app
  namespace: default
spec:
  hosts:
    - pvr-app
  http:
  - route:
    - destination:
        host: pvr-app
        subset: app-v1
      weight: 90
    - destination:
        host: pvr-app
        subset: app-v2
      weight: 10

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pvr-app
  namespace: default
spec:
  host: pvr-app 
  subsets:
  - name: app-v1
    labels:
      version: v1
  - name: app-v2
    labels:
      version: v2