---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: app1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: pvr-app1
        image: eu.gcr.io/parcel-vision/spike-ambassador-application:1.0
        ports:
        - containerPort: 8020
